import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/first-steps',
        'getting-started/upgrading',
        'getting-started/versioning-and-support',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/basic-config',
        'configuration/authorization',
        'configuration/storage',
        'configuration/pruning',
        'configuration/rate-limiting',
        'configuration/alerting',
      ],
    },
    {
      type: 'category',
      label: 'Watchers',
      items: [
        'watchers/overview',
        {
          type: 'category',
          label: 'HTTP',
          items: [
            'watchers/request',
            'watchers/http-client',
          ],
        },
        {
          type: 'category',
          label: 'Database',
          items: [
            'watchers/query',
            'watchers/model',
          ],
        },
        {
          type: 'category',
          label: 'Errors & Logging',
          items: [
            'watchers/exception',
            'watchers/log',
            'watchers/dump',
          ],
        },
        {
          type: 'category',
          label: 'Background Processing',
          items: [
            'watchers/job',
            'watchers/schedule',
            'watchers/batch',
            'watchers/command',
          ],
        },
        {
          type: 'category',
          label: 'Caching',
          items: [
            'watchers/cache',
            'watchers/redis',
          ],
        },
        {
          type: 'category',
          label: 'Communication',
          items: [
            'watchers/mail',
            'watchers/notification',
            'watchers/event',
          ],
        },
        {
          type: 'category',
          label: 'Other',
          items: [
            'watchers/gate',
            'watchers/view',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: [
        'dashboard/overview',
        'dashboard/navigation',
        'dashboard/filtering',
        'dashboard/keyboard-shortcuts',
        'dashboard/live-tail',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/typeorm',
        'integrations/prisma',
        'integrations/bull-bullmq',
        'integrations/redis',
        'integrations/custom-integrations',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/access-control',
        'security/ip-whitelisting',
        'security/network-isolation',
        'security/data-masking',
        'security/production-usage',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/custom-watchers',
        'advanced/extending-storage',
        'advanced/filtering-entries',
        'advanced/performance',
      ],
    },
    'faq',
    {
      /**
       * The reference generated from the source by `docusaurus-plugin-typedoc`.
       *
       * It was written to a directory outside the docs plugin's reach, so none
       * of its pages ever reached the site while the reference readers saw was
       * typed out by hand — and had drifted sixteen interfaces, four config
       * options and the whole GraphQL watcher behind the code.
       *
       * Read from the directory rather than from the sidebar file typedoc
       * writes beside it: this file is evaluated before any plugin runs, so on
       * a clean checkout that sidebar does not exist yet and requiring it took
       * the whole build down. The pages are globbed later, by which time they
       * are there.
       */
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: [{ type: 'autogenerated', dirName: 'api-reference' }],
    },
  ],
};

export default sidebars;
